#!/command/with-contenv bash
# shellcheck shell=bash

# svc-sshd main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[svc-sshd] ${line}"; done) 2>&1

    exec /usr/sbin/sshd -D
}
main
