#!/command/with-contenv bash
# shellcheck shell=bash

# svc-corosync-qnetd main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[svc-corosync-qnetd] ${line}"; done) 2>&1

    exec /usr/bin/corosync-qnetd -f
}
main
